services:
  
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web
    ports:
      - "8000:8000"
    volumes:
      - ~/.gitconfig:/root/.gitconfig
    depends_on:
      db:
        condition: service_healthy
    

  db:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres-data:
