# Generated by Django 4.2 on 2025-03-29 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitorize', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='privatekey',
            old_name='private_key_file',
            new_name='key',
        ),
    ]
