# Generated by Django 4.2 on 2025-04-04 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitorize', '0002_rename_private_key_file_privatekey_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='device',
            name='password',
        ),
        migrations.RemoveField(
            model_name='device',
            name='username',
        ),
        migrations.RemoveField(
            model_name='privatekey',
            name='date_joined',
        ),
    ]
