# Generated by Django 4.2 on 2025-04-12 16:50

from django.db import migrations, models
import django.db.models.deletion
import monitorize.models


class Migration(migrations.Migration):

    dependencies = [
        ('monitorize', '0003_remove_device_date_joined_remove_device_password_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to=monitorize.models.file_upload_path)),
                ('encryption', models.CharField(max_length=255)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitorize.device')),
            ],
        ),
    ]
