# Generated by Django 4.2 on 2025-03-28 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ouruser',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='ouruser',
            name='is_staff',
        ),
    ]
