# Generated by Django 4.2 on 2025-03-31 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_ouruser_is_admin_remove_ouruser_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ouruser',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='ouruser',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='ouruser',
            name='is_superuser',
        ),
        migrations.AlterField(
            model_name='ouruser',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
    ]
